In [1]:
from qibo import Circuit, gates
import tensorflow as tf
import numpy as np

In [12]:
# create a circuit with all parameters set to 0.
c = Circuit(3)
c.add(gates.RX(0, theta=0))
c.add(gates.RX(1, theta=0))
c.add(gates.CNOT(0, 1))

b = Circuit(3)
b.add(gates.RX(0, 0.2))
b.add(gates.RX(1, 1.4))
b.add(gates.CNOT(0,1))

result = c(b().state())




params = [0.123, 0.456]
probs = tf.convert_to_tensor([1,0,0,0,0,0,0,-1])
c.set_parameters(params)
print(result.state())
print(c().state())
print(c.final_state)

tf.Tensor(
[ 0.76102116+0.j          0.        +0.j          0.        -0.64099928j
  0.        +0.j          0.        -0.07635681j  0.        +0.j
 -0.06431445+0.j          0.        +0.j        ], shape=(8,), dtype=complex128)
tf.Tensor(
[ 0.9722788 +0.j          0.        +0.j          0.        -0.22560242j
  0.        +0.j         -0.01389207+0.j          0.        +0.j
  0.        -0.05987065j  0.        +0.j        ], shape=(8,), dtype=complex128)
(0.97228+0j)|000> + -0.2256j|010> + (-0.01389+0j)|100> + -0.05987j|110>


In [3]:
with tf.GradientTape() as tape:
    params = tf.convert_to_tensor([0.5, 0.5])
    tape.watch(params)
    c.set_parameters(params)
    result = c().state()
    amplitudes = tf.cast(result*tf.math.conj(result), dtype = tf.float32)
    cost = amplitudes*probs
    cost = tf.math.reduce_sum(cost)
    

g = tape.gradient(cost, params)


[Qibo 0.2.1|INFO|2023-11-03 14:40:08]: Using tensorflow backend on /device:GPU:0


In [4]:
print(g)

tf.Tensor([-0.23971277 -0.23971277], shape=(2,), dtype=float32)


In [1]:
from PQC_qibo import ReUploadingPQC, generate_circuit
import tensorflow as tf
import numpy as np

In [2]:
qubits = np.arange(4)
model = ReUploadingPQC(qubits, 2, 2)

2023-11-06 16:50:24.254057: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13249 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:d8:00.0, compute capability: 7.5


In [3]:
inputs = tf.convert_to_tensor([1.0,2.0])
inputs = tf.reshape(inputs, shape=(2,1))
print(model(inputs))
probs = np.random.random(2**4)
probs = tf.convert_to_tensor(probs)
with tf.GradientTape() as tape:
    tape.watch(model.circuit.get_parameters())
    amplitudes = model(inputs)
    cost = tf.reduce_sum(amplitudes*probs)
    print("cost")
    print(cost)
    


    
g = tape.gradient(cost, model.circuit.get_parameters())

[Qibo 0.2.1|INFO|2023-11-06 16:50:24]: Using tensorflow backend on /device:GPU:0


tf.Tensor(
[0.0225314  0.0255793  0.35156026 0.01075338 0.00403831 0.05468823
 0.04385179 0.03817671 0.08708753 0.16742066 0.02492792 0.01169796
 0.06447768 0.01700215 0.01999754 0.05621004], shape=(16,), dtype=float32)
cost
tf.Tensor(0.49441600332773017, shape=(), dtype=float64)


In [4]:
print(g)
print(model.circuit.get_parameters())
print(model.thetas)

[(<tf.Tensor: shape=(), dtype=float32, numpy=-0.023078308>,), (<tf.Tensor: shape=(), dtype=float32, numpy=-0.0069445>,), (<tf.Tensor: shape=(), dtype=float32, numpy=-0.0046069226>,), (<tf.Tensor: shape=(), dtype=float32, numpy=0.059497207>,), (<tf.Tensor: shape=(), dtype=float32, numpy=0.012233451>,), (<tf.Tensor: shape=(), dtype=float32, numpy=-0.058154285>,), (<tf.Tensor: shape=(), dtype=float32, numpy=0.050007127>,), (<tf.Tensor: shape=(), dtype=float32, numpy=-0.05452776>,), (<tf.Tensor: shape=(), dtype=float32, numpy=-0.03984002>,), (<tf.Tensor: shape=(), dtype=float32, numpy=-0.112909555>,), (<tf.Tensor: shape=(), dtype=float32, numpy=0.030215733>,), (<tf.Tensor: shape=(), dtype=float32, numpy=0.028353613>,), (<tf.Tensor: shape=(), dtype=float32, numpy=0.052985325>,), (<tf.Tensor: shape=(), dtype=float32, numpy=-0.005341187>,), (<tf.Tensor: shape=(), dtype=float32, numpy=0.05298534>,), (<tf.Tensor: shape=(), dtype=float32, numpy=-0.007346142>,), (<tf.Tensor: shape=(), dtype=float

In [ ]:
circuit = qibo.Circuit(5)